"""
Stage 7 — Refinement Loop
See plan/ARCHITECTURE.md, Stage 7, and plan/EVALUATION.md, "Claim 2" for
the full honest validation methodology.

Real (or, pre-deployment, simulated) quiz-performance patterns are used as
weak supervision to correct the graph over time: if many students
consistently fail concept B right after struggling with concept A, that
becomes evidence reinforcing (or contradicting) the graph's assumed A->B
edge.

The synthetic-student recovery experiment (the project's most original
piece, and the one requiring the most care to present honestly) is kept
separate from anything touching real quiz data — see plan/LIMITATIONS.md #5.

  run_refinement_round(graph, mastery, n_students)
      -> adjust edge confidences from observed directional mastery signals.

  generate_synthetic_students(hidden_graph, n, completer=...)
      -> LLM-persona synthetic students (Claim 2): each persona is prompted
         to roleplay a student taught a randomized subset of the hidden
         graph's concepts, then genuinely attempts one knowledge-check per
         concept, producing realistic, patterned errors driven by the gaps
         in its taught set. `completer` is injectable so tests run offline
         with a fake; the default is llm.complete (cached, quota-metered).

  score_recovery(guessed_graph, hidden_graph)
      -> precision/recall/F1 of guessed edges vs. the hidden ground truth,
         for "before vs. after refinement" convergence reporting.
"""

from typing import Dict, List


def _edges_of(graph: Dict) -> List[Dict]:
    if isinstance(graph, dict):
        return list(graph.get("edges", []))
    return list(graph.edges())


def run_refinement_round(
    graph: Dict,
    failures: Dict[str, List[str]],
    n_students: int,
) -> "tuple[List[Dict], Dict]":
    """Adjust the graph's edge confidences from observed co-failure signals.

    Weak-supervision rule, faithful to the plan's Stage 7 wording: "if many
    students consistently FAIL concept B right after struggling with concept
    A, that becomes evidence reinforcing (or contradicting) the graph's
    assumed A->B edge." Concretely, per directed edge A->B:

        support      = fraction who FAILED A *and* FAILED B
                       (B fails together with A -> B plausibly depends on A)
        contradict   = fraction who FAILED A *but* DID NOT fail B
                       (B is fine while A fails -> B does NOT need A)

    The updated confidence blends the graph's prior confidence with this
    directional evidence:

        c' = clamp(0.5 * prior + 0.5 * P(failB | failA))

    where P(failB | failA) = support / (support + contradict). A true edge
    (A->B) keeps B failing whenever A fails, so the ratio stays high and the
    edge rises; a spurious edge (A->I where I is easy/independent) has I
    succeed even when A fails, so the ratio collapses and the edge sinks
    below threshold.

    `failures` maps student_id -> sorted list of concepts that student got
    WRONG (the weak-supervision signal generated by the LLM personas).
    `n_students` is the number of students seen, for normalization.

    Returns (updated_edges, summary). Pure — persistence is the caller's job.
    """
    edges = _edges_of(graph)
    n = max(1, n_students)
    fail = {sid: set(concepts) for sid, concepts in failures.items()}
    out = []
    for e in edges:
        src, tgt = e["source"], e["target"]
        prior = float(e.get("confidence", 0.5))
        fail_src = [sid for sid, s in fail.items() if src in s]
        both = [sid for sid in fail_src if tgt in fail[sid]]
        src_not_tgt = [sid for sid in fail_src if tgt not in fail[sid]]

        support = len(both) / n
        contradict = len(src_not_tgt) / n
        cond = support / (support + contradict) if (support + contradict) else 0.0

        updated = min(1.0, max(0.0, 0.5 * prior + 0.5 * cond))
        out.append({"source": src, "target": tgt, "confidence": updated})

    return out, {"edges_updated": len(out), "n_students": n_students}


def score_recovery(
    guessed_graph: Dict, hidden_graph: Dict, threshold: float = 0.5
) -> Dict:
    """Precision/recall/F1 of the guessed graph's edges against the hidden
    ground truth — the "before vs. after refinement" convergence metric.

    A guessed edge counts as present only if its confidence is >= `threshold`
    (so the loop is scored on the strength-weighted edge set). Refinement
    raises true edges above threshold and sinks spurious ones below it, which
    is what makes the before/after F1 move.
    """
    guessed = {
        (e["source"], e["target"])
        for e in _edges_of(guessed_graph)
        if float(e.get("confidence", 0.0)) >= threshold
    }
    hidden_set = {(e["source"], e["target"]) for e in _edges_of(hidden_graph)}

    correct = len(guessed & hidden_set)
    precision = correct / len(guessed) if guessed else 0.0
    recall = correct / len(hidden_set) if hidden_set else 0.0
    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) else 0.0
    )
    return {"precision": precision, "recall": recall, "f1": f1,
            "correct_edges": correct, "guessed_edges": len(guessed),
            "hidden_edges": len(hidden_set)}


def _concepts_of(graph: Dict) -> List[str]:
    """All concept names appearing in a graph (dict or networkx form)."""
    if isinstance(graph, dict):
        return sorted({e["source"] for e in _edges_of(graph)} |
                      {e["target"] for e in _edges_of(graph)})
    return sorted(graph.nodes())


def generate_synthetic_students(
    hidden_graph: Dict,
    n: int,
    seed: int = 42,
    completer=None,
    temperature: float = 0.0,
) -> List[Dict]:
    """LLM-persona synthetic students (Claim 2 controlled recovery).

    Per plan/EVALUATION.md Claim 2, each synthetic student is an LLM persona
    that has been *taught* a defined, randomized subset of the hidden graph's
    concepts, and the LLM then genuinely attempts a knowledge-check for every
    concept given that taught set. This produces realistic, *patterned*
    errors: a persona asked about a concept it wasn't taught — or one whose
    prerequisite it wasn't taught — tends to fail it, even when it mastered
    its prerequisites. These are the behavioral signals the refinement loop
    is then scored against (the module's tests pass a fake `completer` so the
    unit suite stays offline).

    `completer(system, user, temperature=...) -> object with `.text``. When
    omitted, defaults to `backend.pipeline.llm.complete` (cached by prompt, so
    identical persona+question prompts are never re-billed). `temperature`
    defaults to 0 for reproducible reasoning.

    Returns one dict per student: `{"id", "taught", "mastered", "failed"}`.
        taught   - the randomized subset the persona was taught (input).
        mastered - concepts the persona answered PASS (ground-truth mastery).
        failed   - concepts the persona answered FAIL (the co-failure signal).
    `run_refinement_round` should consume `mastered` as its mastery signal.
    """
    import random

    rng = random.Random(seed)
    all_concepts = _concepts_of(hidden_graph)
    if not all_concepts:
        return []

    if completer is None:
        # Lazy import: keep llm (Groq/Ollama client) out of module import time.
        from backend.pipeline import llm as _llm

        def _default_completer(system, user, *, temperature):
            return _llm.complete(system, user, temperature=temperature)

        completer = _default_completer

    edges = _edges_of(hidden_graph)
    deps = "\n".join(
        f"- {e['target']} requires {e['source']}" for e in edges
    ) or "(none)"

    students = []
    for i in range(n):
        k = rng.randint(max(1, len(all_concepts) // 2), len(all_concepts))
        taught = set(rng.sample(all_concepts, k))
        system = (
            "You are a student taking a course. You were taught only a limited "
            "set of topics, and you have NOT learned anything beyond that set.\n"
            "The course material establishes these dependencies:\n"
            f"{deps}\n"
            "You reason carefully: if a topic requires a prerequisite that was "
            "NOT in your taught set, you have not mastered that topic even if "
            "you learned the prerequisite's name from reading the syllabus."
        )
        mastered, failed = [], []
        for concept in all_concepts:
            user = (
                f"Topics you were actually taught: "
                f"{', '.join(sorted(taught)) or '(none)'}\n"
                f"Topic under test: {concept}\n"
                "\nReply with EXACTLY one line. First word must be PASS or FAIL, "
                "then at most one sentence explaining your reasoning about "
                "whether (and why) you have mastered this topic."
            )
            resp = completer(system, user, temperature=temperature)
            text = (getattr(resp, "text", "") or "").strip()
            if text.upper().startswith("PASS"):
                mastered.append(concept)
            else:
                failed.append(concept)
        students.append({
            "id": f"s{i}",
            "taught": sorted(taught),
            "mastered": sorted(mastered),
            "failed": sorted(failed),
        })
    return students