"""
Generate a committed FUNCTION_MAP for staying-in-context across sessions.

Scans every tracked Python module and records, per module:
  * the functions/methods it DEFINES
  * the backend symbols it IMPORTS (top-level and lazy in-function imports)
  * the pipeline functions it references as strings (quick-search aid)

This is a static inventory (not a call-graph); it answers "which module do I
edit to change X?" and "who depends on function Y?" without reading the whole
codebase. Regenerate with:

    python scripts/make_function_map.py      # -> plan/FUNCTION_MAP.md

Run it after each phase lands so the map stays current (workflow step).
"""

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "plan" / "FUNCTION_MAP.md"

MODULES = [
    "backend/main.py",
    "backend/config.py",
    "backend/api/schemas.py",
    "backend/api/queries.py",
    "backend/api/graphs.py",
    "backend/api/jobs/common.py",
    "backend/api/jobs/progress.py",
    "backend/api/jobs/transcribe.py",
    "backend/api/jobs/extract.py",
    "backend/api/jobs/clips.py",
    "backend/api/jobs/graph.py",
    "backend/api/jobs/purge.py",
    "backend/api/routes/__init__.py",
    "backend/api/routes/lectures.py",
    "backend/api/routes/courses.py",
    "backend/api/routes/quizzes.py",
    "backend/models/db.py",
    "backend/pipeline/llm.py",
    "backend/pipeline/transcribe.py",
    "backend/pipeline/extract_concepts.py",
    "backend/pipeline/passages.py",
    "backend/pipeline/classify_prerequisites.py",
    "backend/pipeline/build_graph.py",
    "backend/pipeline/segment_clips.py",
    "experiments/fine_tune.py",
    "experiments/refine.py",
    "frontend/client.py",
    "frontend/student_app.py",
    "frontend/faculty_app.py",
]


def _backend_imports(tree: ast.Module):
    """Set of backend symbol names imported by a module (any import stmt)."""
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.startswith("backend"):
                    names.add(a.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.startswith("backend"):
                for a in node.names:
                    names.add(f"{node.module}.{a.name}" if a.name != "*" else node.module)
    return sorted(names)


def _top_defined(tree: ast.Module):
    """Top-level function definitions (incl. class methods) with line numbers."""
    out = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            out.append((node.name, node.lineno, ""))
        elif isinstance(node, ast.ClassDef):
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    out.append((f"{node.name}.{sub.name}", sub.lineno, "class method"))
    return out


def scan(path: Path) -> tuple:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return _top_defined(tree), _backend_imports(tree)


def main() -> None:
    lines = [
        "# FUNCTION_MAP",
        "",
        "Auto-generated by `python scripts/make_function_map.py` (regenerate after",
        "each phase). Static inventory — module-level, function-granularity: what",
        "each module defines and which backend symbols it consumes. Not a call graph.",
        "",
    ]
    for rel in MODULES:
        path = REPO / rel
        if not path.exists():
            lines.append(f"## {rel} *(missing)*\n")
            continue
        defs, imports = scan(path)
        rel_dot = rel.replace("/", ".")
        lines += [f"## {rel_dot}", ""]
        if defs:
            lines.append("Defines:")
            for name, lineno, kind in defs:
                suffix = f"  *({kind})*" if kind else ""
                lines.append(f"- `{name}` — line {lineno}{suffix}")
        else:
            lines.append("Defines: *(none — script/module)*")
        lines.append("")
        if imports:
            lines.append("Consumes from `backend.*`:")
            for imp in imports:
                lines.append(f"- `{imp}`")
        else:
            lines.append("Consumes from `backend.*`: *(none)*")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
    sys.exit(0)